version: '3.5'

services:
  # app:
  #   build: .
  #   container_name: app
  #   image: app
  #   environment:
  #     PG_URL: 'postgres://admin:root@postgres:5432/postgres'
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres

  postgres:
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    image: postgres:15-alpine

volumes:
  pg-data: 
